Changes in:  gstreamer gst-plugins-bad
 gstreamer:7e5dc030f5e39998169166a8b1a734f3bf7efc62
 gst-plugins-base:fdfc6baf14766e14918fdbc39bc18366e7f89c59
 gst-plugins-good:52d0588c21be1a9b85e531fd399cdaaf6198507e
 gst-plugins-ugly:1e74f611ee8d1c6d65d0e7963ef5dc276a07e092
 gst-plugins-bad:7ec5f8527ae74462aa98b7badbfbcdbb3808e31e
 gst-ffmpeg:e9e31ebada6cae34169d26249da0420c96d69cb0
 gnonlin:814737dc14c33737a01ee96c17dbb8ec51b85f91
 gst-editing-services:219154eacb16867be7d0e2274227a62072d70f39
 gst-python:25a0d4b8f91f1d771c215079832170cd0402d2ee

====== gstreamer =============

 commit 7e5dc030f5e39998169166a8b1a734f3bf7efc62
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Wed Oct 30 21:53:36 2013 +0100

    utils: Add some attributes and reorganize code to fix compiler warnings

    gstutils.c:3659:41: error: format string is not a string literal
    [-Werror,-Wformat-nonliteral]
        gchar *expanded = g_strdup_vprintf (stream_id, var_args);

    https://bugzilla.gnome.org/show_bug.cgi?id=710621

====== gst-plugins-bad =============