Changes in:  gst-plugins-good
 gstreamer:7e5dc030f5e39998169166a8b1a734f3bf7efc62
 gst-plugins-base:ddf4ca22033a390fa26c16d717da8e13da3cd567
 gst-plugins-good:a22d61007aa7bf539ae735dbab6026d44729fe61
 gst-plugins-ugly:1e74f611ee8d1c6d65d0e7963ef5dc276a07e092
 gst-plugins-bad:786f5e4f7c7cb9da0eac06215c0c274f74eb40ce
 gst-ffmpeg:e9e31ebada6cae34169d26249da0420c96d69cb0
 gnonlin:814737dc14c33737a01ee96c17dbb8ec51b85f91
 gst-editing-services:219154eacb16867be7d0e2274227a62072d70f39
 gst-python:25a0d4b8f91f1d771c215079832170cd0402d2ee

====== gst-plugins-good =============

 commit a22d61007aa7bf539ae735dbab6026d44729fe61
Author: Djalma Lúcio Soares da Silva <dlucio@impa.br>
Date:   Thu Oct 31 13:02:11 2013 -0200

    hdv1394src: Make it possible to select a camera by its GUID

    The source hdv1394src has the guid property that permits select a camera
    connected from its GUID number.
    However when this property is setted the selected camera is not changed.
    The source continues using the default camera.

    This problem was solved using the function iec61883_cmp_connect.
    The reference for the function could be found here:
    http://www.dennedy.org/libiec61883/API-iec61883-cmp-connect.html

    The solution came from dvgrab source code.

    https://bugzilla.gnome.org/show_bug.cgi?id=710415

commit 43602e2d8a7d18c2804e883719eaaa479df1fa65
Author: Thiago Santos <ts.santos@partner.samsung.com>
Date:   Thu Oct 31 13:20:41 2013 -0300

    tests: souphttpsrc: add explicit cast to silence warning

    Silencing this warning:

    elements/souphttpsrc.c:533:14: error: comparison between ‘SoupKnownStatusCode’ and ‘enum <anonymous>’ [-Werror=enum-compare]
       if (status != SOUP_STATUS_OK && !send_error_doc)

    With gcc 4.8.2 (debian)