Changes in:  gst-plugins-good
 gstreamer:6db013ff7c6b469da67fd3f96d13a091f147f424
 gst-plugins-base:ea45653db9d5e7b1e7b4793bea5e3de219666ade
 gst-plugins-good:94ad6724ba5c0136d385cc0f052db636bf99a86c
 gst-plugins-ugly:ec830e755840969f35c83ebb67756b1c1b5258e9
 gst-plugins-bad:ad2c27082d92bca37bde43ffece21cf37b96c961
 gst-ffmpeg:2d63ac0af65fc1d0a66049cf919b0ac787cbcb54
 gnonlin:84534369b4e96432d73a8cefda4b4962e8a4b8ff
 gst-editing-services:56754358f419fc6d1683f423f45413c48f951190
 gst-python:20860bc63376944cc7749255123e201feec5f39c

====== gst-plugins-good =============

 commit 94ad6724ba5c0136d385cc0f052db636bf99a86c
Author: Sebastian Dröge <slomo@circular-chaos.org>
Date:   Sat Sep 21 18:46:29 2013 +0200

    goom: Fix MMX assembly compilation with clang

    clang does not want or need a clobber list for emms:
    error: clobbers must be last on the x87 stack

    Patch taken from the FreeBSD ports, provided by
    Dan McGregor <dan.mcgregor@usask.ca>