Changes in:  gst-plugins-base gst-plugins-good
 gstreamer:73a58cb0a2b861df6c20a8c30747117562fa7523
 gst-plugins-base:1d40b1d2bb68963941720c588bfcc94d6fa3f939
 gst-plugins-good:b8f689a9d97b7a90a3c40d5249c964e35a000b4a
 gst-plugins-ugly:8c1be8796e58bfcab7c9b9ac2ca089b10bf803b4
 gst-plugins-bad:1b747bfecb6d36854aa19fbc6293676cc5eef390
 gst-ffmpeg:40d9f00106ada79a3e7ea110630021aff4102ed2
 gnonlin:1c93a9c581b19d682630866761f41db58b226de3
 gst-editing-services:e7a45f0eef880a5530431c8ae1984a85169921d6
 gst-python:2ad767a74c4dc950344865513604b87d6202dc46

====== gst-plugins-base =============

 commit 1d40b1d2bb68963941720c588bfcc94d6fa3f939
Author: Tim-Philipp Müller <tim@centricular.com>
Date:   Thu Nov 28 16:22:01 2013 +0000

    tcp: fix compilation with MSVC

    error C2440 at line 165 of gsttcpserversink.c
    type cast error: cannot convert from GSocket* to GstMultiSinkHandle

====== gst-plugins-good =============

 commit b8f689a9d97b7a90a3c40d5249c964e35a000b4a
Author: Tim-Philipp Müller <tim@centricular.com>
Date:   Thu Nov 28 16:09:04 2013 +0000

    videoflip: don't crash on tag events without orientation tag

    Would crash in g_free() trying to free an uninitialised pointer.

    https://bugzilla.gnome.org/show_bug.cgi?id=719497