Changes in:  gst-plugins-base
 gstreamer:3dc8ee97e50039c73fc322f687741a5b7193b750
 gst-plugins-base:d7775cffb99c9fc63757c0e6d665bd1bce523633
 gst-plugins-good:60e72b02544104935329f0d46e932384cf95c179
 gst-plugins-ugly:0243810e1e0d35fff1023d3f6c42967cc7aaff6e
 gst-plugins-bad:8fb662884232c6840a094c0d40b54888e3efd6c3
 gst-ffmpeg:61153a5ac231141e4395b9f0bb28a26fa808a098
 gnonlin:79624b830af08437d9a17464ba688c6a228f790b
 gst-editing-services:28770ce53b97678dcd7e5d981e748f643bc9c8cd
 gst-python:20860bc63376944cc7749255123e201feec5f39c

====== gst-plugins-base =============

 commit d7775cffb99c9fc63757c0e6d665bd1bce523633
Author: Tim-Philipp Müller <tim@centricular.net>
Date:   Fri Sep 6 13:28:00 2013 +0100

    video: fix build without orc or older or versions

    ./.libs/libgstvideo-1.0.so: undefined reference to `video_orc_unpack_NV24'
    ./.libs/libgstvideo-1.0.so: undefined reference to `video_orc_pack_NV24'