Changes in:  gst-plugins-base gst-plugins-good gst-plugins-bad
 gstreamer:56d74ddb644052dc76d97c22b9f284cc0c7fe35a
 gst-plugins-base:9011bc1b54ba3f54255b3171f005eda29f7bac5c
 gst-plugins-good:4278ab18ff04afce90648bd9fea0ee72e327488b
 gst-plugins-ugly:8c1be8796e58bfcab7c9b9ac2ca089b10bf803b4
 gst-plugins-bad:00dec2e74368dba0f6efbeeb99ae4a0112c019d9
 gst-ffmpeg:40d9f00106ada79a3e7ea110630021aff4102ed2
 gnonlin:dd148c43ad4c8d09a659093024e210949e5eb1e0
 gst-editing-services:289b04f170ddfa28ec4bc01794a8ef444b61a8b4
 gst-python:2ad767a74c4dc950344865513604b87d6202dc46

====== gst-plugins-base =============

 commit 9011bc1b54ba3f54255b3171f005eda29f7bac5c
Author: Tim-Philipp Müller <tim@centricular.com>
Date:   Fri Nov 29 09:04:20 2013 +0000

    tools: gst-play: quit on Q or Esc key

====== gst-plugins-good =============

 commit 4278ab18ff04afce90648bd9fea0ee72e327488b
Author: Tim-Philipp Müller <tim@centricular.com>
Date:   Fri Nov 29 09:21:52 2013 +0000

    qtdemux: fix compilation with gst debuging disabled

    qtdemux.c:9452:1: error: label at end of compound statement

====== gst-plugins-bad =============

 commit 00dec2e74368dba0f6efbeeb99ae4a0112c019d9
Author: Christian Fredrik Kalager Schaller <uraeus@linuxrising.org>
Date:   Fri Nov 29 10:14:43 2013 +0100

    Update spec file with latest changes