Changes in:  gst-plugins-base gst-plugins-good
 gstreamer:7e5dc030f5e39998169166a8b1a734f3bf7efc62
 gst-plugins-base:ddf4ca22033a390fa26c16d717da8e13da3cd567
 gst-plugins-good:4a8082856aca644994a9a2839bf06998340c2164
 gst-plugins-ugly:1e74f611ee8d1c6d65d0e7963ef5dc276a07e092
 gst-plugins-bad:7ec5f8527ae74462aa98b7badbfbcdbb3808e31e
 gst-ffmpeg:e9e31ebada6cae34169d26249da0420c96d69cb0
 gnonlin:814737dc14c33737a01ee96c17dbb8ec51b85f91
 gst-editing-services:219154eacb16867be7d0e2274227a62072d70f39
 gst-python:25a0d4b8f91f1d771c215079832170cd0402d2ee

====== gst-plugins-base =============

 commit ddf4ca22033a390fa26c16d717da8e13da3cd567
Author: Thibault Saunier <thibault.saunier@collabora.com>
Date:   Wed Oct 16 16:46:05 2013 -0300

    playback: Add subpicture/x-dvb as raw caps

    https://bugzilla.gnome.org/show_bug.cgi?id=710325

====== gst-plugins-good =============

 commit 4a8082856aca644994a9a2839bf06998340c2164
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Wed Oct 30 22:12:45 2013 +0100

    matroska-demux: Fix compiler warning

    matroska-demux.c: In function 'gst_matroska_demux_add_stream':
    matroska-demux.c:1379:7: error: format '%u' expects argument of type 'unsigned int', but argument 4 has type 'guint64' [-Werror=format=]
           "%03u", context->uid);
           ^