Changes in:  gstreamer gst-plugins-good
 gstreamer:71ad1d6fdd39840b770bfa03a2822b68eee57df9
 gst-plugins-base:57295753d54da55289f50d4b2585cb234d3fedd0
 gst-plugins-good:cf31a4284bcd87f4137bdd8f2dc1cf3cedf43ccb
 gst-plugins-ugly:abb56c3803f9c703f7046bf02e024df8937504fe
 gst-plugins-bad:eef356c80f2eef7bbdc78a9930083cb940a632b3
 gst-ffmpeg:fe224775cfa13b442d73ab76e7b2d5cdd491ef75
 gnonlin:242e4e17d91be1864cad4f8193b7508e00677e52
 gst-editing-services:0a25ed00a19cc150333510e55deaa50b8cbdd9a7
 gst-python:c889037e40bb3568ef8cd9456123d744b25a919b

====== gstreamer =============

 commit 71ad1d6fdd39840b770bfa03a2822b68eee57df9
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Tue Feb 11 13:27:25 2014 +0100

    error: GST_RESOURCE_ERROR_NOT_AUTHORIZED will be available since 1.2.4

commit 8a96585eeecde2033387ffad8bedcc834326fdb5
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Tue Feb 11 13:09:11 2014 +0100

    error: Add RESOURCE_NOT_AUTHORIZED error

    This allows to distinguish normal read failures from read failures
    where we miss authorization.

====== gst-plugins-good =============

 commit cf31a4284bcd87f4137bdd8f2dc1cf3cedf43ccb
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Tue Feb 11 13:25:46 2014 +0100

    souphttpsrc: Add mapping for NOT_FOUND and NOT_AUTHORIZED errors

commit 5514bc2785efbe5922c86f7ffe558a0518c5d403
Author: Sebastian Dröge <sebastian@centricular.com>
Date:   Tue Feb 11 13:25:22 2014 +0100

    souphttpsrc: Don't duplicate status_code to GStreamer error mapping